name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Docker Build
        run: |
          docker build -t featuredrift:latest .

      - name: Push to GHCR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag featuredrift:latest ghcr.io/${{ github.repository_owner }}/featuredrift:latest
          docker push ghcr.io/${{ github.repository_owner }}/featuredrift:latest
