name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Docker Build
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/featuredrift-web:latest .

      - name: Push to GHCR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.repository_owner }}/featuredrift-web:latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Install kubeconfig for DigitalOcean
        run: |
          doctl kubernetes cluster kubeconfig save thezanke-k8s-do-2
          echo "Kubeconfig installed"
        
      - name: Deploy to DigitalOcean
        run: |
          kubectl rollout restart deployment featuredrift-web -n apps
